package Vistas;

import Clases.Autocompleter;
import Clases.Cargando;
import Clases.Tools;
import Clases.X;
import General.userAuth;
import Objects.cbx_content;
import Secciones.Clientes;
import Secciones.Inventario;
import Secciones.Usuarios;
import Secciones.Venta;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Abdi
 */
public class Home extends javax.swing.JFrame {

    boolean menu = false;

    public ImageIcon bien = new ImageIcon(getClass().getResource("/Images/bien.png"));

    public TextAutoCompleter buscadorcod, sugerenciasventas;

    private Usuarios usuarios;
    private Clientes clientes;
    private Inventario inventario;

    public Home() {
        initComponents();
        setTitle("Ventas");
        setLocationRelativeTo(null);
        jPanel1.setComponentZOrder(jP_menuprincipal, 0);
        jPanel1.setComponentZOrder(jP_sombreado, 1);
        jPanel1.setComponentZOrder(jPanel3, 2);
        jPanel1.repaint();
        
        Tools.anim_icon_button(btn_menu, () -> this.menu);
        Tools.addButtonEffects(btn_menu, () -> this.menu);

        UtilPanels p = new UtilPanels();
        inventario = new Inventario(this, p);
        usuarios = new Usuarios(this, p);
        clientes = new Clientes(this, p);

        jP_sombreado.setVisible(false);
        repaint();
        menu_roll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupNventa = new javax.swing.JPopupMenu();
        jMenuItemEliminar = new javax.swing.JMenuItem();
        jMenuItemeliminartodo = new javax.swing.JMenuItem();
        jPopupInventario = new javax.swing.JPopupMenu();
        item_addStock_inv = new javax.swing.JMenuItem();
        item_editar_inv = new javax.swing.JMenuItem();
        item_estado_inv = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jP_menuprincipal = new javax.swing.JPanel();
        jL_ventas = new javax.swing.JLabel();
        jL_inventarios = new javax.swing.JLabel();
        jL_clientes = new javax.swing.JLabel();
        jL_caja = new javax.swing.JLabel();
        jL_usuarios = new javax.swing.JLabel();
        jL_configuracion = new javax.swing.JLabel();
        jL_cerrarsesion = new javax.swing.JLabel();
        jL_wallpaper = new javax.swing.JLabel();
        jP_sombreado = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_menu = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jP_ventas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableNventa = new javax.swing.JTable();
        jL_totalapagar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_buscadorproductos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jP_caja = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jP_inventario = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInventario = new javax.swing.JTable();
        jP_buscadorusuarios1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_buscador_inventario = new javax.swing.JTextField();
        btn_nvprod_inv = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel_pags_inv = new javax.swing.JLabel();
        btn_anteriorpag_inv = new javax.swing.JLabel();
        btn_sigpag_inv = new javax.swing.JLabel();
        jP_clientes = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        scroll_clientes = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        btn_registrarcliente = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jP_buscadorcliente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_buscador_cliente = new javax.swing.JTextField();
        jP_usuarios = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        scroll_usuarios = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        btn_registrarusuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jP_buscadorusuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_buscadorp_usuario = new javax.swing.JTextField();
        jP_confi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jP_HistorialVentas = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();

        jMenuItemEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        jMenuItemEliminar.setText("Eliminar producto");
        jMenuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEliminarActionPerformed(evt);
            }
        });
        jPopupNventa.add(jMenuItemEliminar);

        jMenuItemeliminartodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminartodo.png"))); // NOI18N
        jMenuItemeliminartodo.setText("Eliminar todo");
        jMenuItemeliminartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemeliminartodoActionPerformed(evt);
            }
        });
        jPopupNventa.add(jMenuItemeliminartodo);

        ImageIcon iconAddStock = Tools.escalarIcono(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png")), 22, 22);
        item_addStock_inv.setIcon(iconAddStock);
        item_addStock_inv.setText("agregar stock");
        item_addStock_inv.setToolTipText("");
        item_addStock_inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_addStock_invActionPerformed(evt);
            }
        });
        jPopupInventario.add(item_addStock_inv);

        ImageIcon iconEdit = Tools.escalarIcono(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit_icon-icons.com_71853.png")), 32, 32);
        item_editar_inv.setIcon(iconEdit);
        item_editar_inv.setText("Editar");
        item_editar_inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_editar_invActionPerformed(evt);
            }
        });
        jPopupInventario.add(item_editar_inv);

        ImageIcon iconEstado = Tools.escalarIcono(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png")), 17, 17);
        item_estado_inv.setIcon(iconEstado);
        item_estado_inv.setText("Inactivar");
        jPopupInventario.add(item_estado_inv);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jP_menuprincipal.setBackground(new java.awt.Color(33, 45, 62));
        jP_menuprincipal.setLayout(new java.awt.GridBagLayout());

        jL_ventas.setBackground(new java.awt.Color(33, 45, 62));
        jL_ventas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jL_ventas.setForeground(new java.awt.Color(255, 255, 255));
        jL_ventas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping_cart_icon_156961.png"))); // NOI18N
        jL_ventas.setText("Venta");
        jL_ventas.setToolTipText("");
        jL_ventas.setDisabledIcon(null);
        jL_ventas.setFocusable(false);
        jL_ventas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jL_ventas.setOpaque(true);
        jL_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_ventasMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 118;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 2);
        jP_menuprincipal.add(jL_ventas, gridBagConstraints);

        jL_inventarios.setBackground(new java.awt.Color(33, 45, 62));
        jL_inventarios.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jL_inventarios.setForeground(new java.awt.Color(255, 255, 255));
        jL_inventarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_inventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/travel_package_transport_shipping_box_delivery_icon_227300.png"))); // NOI18N
        jL_inventarios.setText("Inventario");
        jL_inventarios.setOpaque(true);
        jL_inventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_inventariosMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 2);
        jP_menuprincipal.add(jL_inventarios, gridBagConstraints);

        jL_clientes.setBackground(new java.awt.Color(33, 45, 62));
        jL_clientes.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jL_clientes.setForeground(new java.awt.Color(255, 255, 255));
        jL_clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Users_40957 (1).png"))); // NOI18N
        jL_clientes.setText("Clientes");
        jL_clientes.setOpaque(true);
        jL_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_clientesMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 2);
        jP_menuprincipal.add(jL_clientes, gridBagConstraints);

        jL_caja.setBackground(new java.awt.Color(33, 45, 62));
        jL_caja.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jL_caja.setForeground(new java.awt.Color(255, 255, 255));
        jL_caja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_caja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cash_register_icon_192649.png"))); // NOI18N
        jL_caja.setText("Caja");
        jL_caja.setOpaque(true);
        jL_caja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cajaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 2);
        jP_menuprincipal.add(jL_caja, gridBagConstraints);

        jL_usuarios.setBackground(new java.awt.Color(33, 45, 62));
        jL_usuarios.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jL_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        jL_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1495573745-jd06_84493.png"))); // NOI18N
        jL_usuarios.setText("Usuarios");
        jL_usuarios.setOpaque(true);
        jL_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_usuariosMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 76;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 2);
        jP_menuprincipal.add(jL_usuarios, gridBagConstraints);

        jL_configuracion.setBackground(new java.awt.Color(33, 45, 62));
        jL_configuracion.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jL_configuracion.setForeground(new java.awt.Color(255, 255, 255));
        jL_configuracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/configuration2.png"))); // NOI18N
        jL_configuracion.setText("Configuración");
        jL_configuracion.setOpaque(true);
        jL_configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_configuracionMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 2);
        jP_menuprincipal.add(jL_configuracion, gridBagConstraints);

        jL_cerrarsesion.setBackground(new java.awt.Color(33, 45, 62));
        jL_cerrarsesion.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jL_cerrarsesion.setForeground(new java.awt.Color(255, 255, 255));
        jL_cerrarsesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout (2).png"))); // NOI18N
        jL_cerrarsesion.setText("Cerrar sesión");
        jL_cerrarsesion.setOpaque(true);
        jL_cerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_cerrarsesionMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 2);
        jP_menuprincipal.add(jL_cerrarsesion, gridBagConstraints);

        jL_wallpaper.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jL_wallpaper.setForeground(new java.awt.Color(255, 255, 255));
        jL_wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_wallpaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_wallpaperMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 630;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        jP_menuprincipal.add(jL_wallpaper, gridBagConstraints);

        jPanel1.add(jP_menuprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 200, -1));

        jP_sombreado.setBackground(new Color(0,0,0,0.5f));
        jP_sombreado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jP_sombreadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jP_sombreadoLayout = new javax.swing.GroupLayout(jP_sombreado);
        jP_sombreado.setLayout(jP_sombreadoLayout);
        jP_sombreadoLayout.setHorizontalGroup(
            jP_sombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
        );
        jP_sombreadoLayout.setVerticalGroup(
            jP_sombreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jP_sombreado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 840));

        jPanel3.setBackground(new java.awt.Color(248, 248, 248));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Menu_icon_icon-icons.com_71858.png"))); // NOI18N
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menuMouseClicked(evt);
            }
        });
        jPanel3.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 40));

        jP_ventas.setBackground(new java.awt.Color(248, 248, 248));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tableNventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Código", "Descripcion", "Precio", "Cantidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNventa.setComponentPopupMenu(jPopupNventa);
        tableNventa.setDoubleBuffered(true);
        jScrollPane3.setViewportView(tableNventa);
        if (tableNventa.getColumnModel().getColumnCount() > 0) {
            tableNventa.getColumnModel().getColumn(0).setMinWidth(0);
            tableNventa.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableNventa.getColumnModel().getColumn(0).setMaxWidth(0);
            tableNventa.getColumnModel().getColumn(1).setResizable(false);
            tableNventa.getColumnModel().getColumn(2).setResizable(false);
            tableNventa.getColumnModel().getColumn(3).setResizable(false);
            tableNventa.getColumnModel().getColumn(4).setResizable(false);
            tableNventa.getColumnModel().getColumn(5).setResizable(false);
        }

        jL_totalapagar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jL_totalapagar.setForeground(new java.awt.Color(0, 102, 102));
        jL_totalapagar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_totalapagar.setText("0.00");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Total a pagar: Q.");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Buscar producto");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 40));

        txt_buscadorproductos.setBorder(null);
        txt_buscadorproductos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_buscadorproductosFocusLost(evt);
            }
        });
        txt_buscadorproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscadorproductosMouseClicked(evt);
            }
        });
        txt_buscadorproductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscadorproductosKeyReleased(evt);
            }
        });
        jPanel4.add(txt_buscadorproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_locate_find_icon-icons.com_67287.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 0, 50, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/business-color_handout_icon-icons.com_53455.png"))); // NOI18N
        jButton2.setText("Generar venta");

        javax.swing.GroupLayout jP_ventasLayout = new javax.swing.GroupLayout(jP_ventas);
        jP_ventas.setLayout(jP_ventasLayout);
        jP_ventasLayout.setHorizontalGroup(
            jP_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ventasLayout.createSequentialGroup()
                .addGroup(jP_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_ventasLayout.createSequentialGroup()
                        .addGap(990, 990, 990)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_totalapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_ventasLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jP_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_ventasLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3131, 3131, 3131))
        );
        jP_ventasLayout.setVerticalGroup(
            jP_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ventasLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jP_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jP_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_totalapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(196, 196, 196))
        );

        jTabbedPane1.addTab("tab2", jP_ventas);

        jLabel4.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel4.setText("Caja");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jP_cajaLayout = new javax.swing.GroupLayout(jP_caja);
        jP_caja.setLayout(jP_cajaLayout);
        jP_cajaLayout.setHorizontalGroup(
            jP_cajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cajaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jP_cajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(4221, Short.MAX_VALUE))
        );
        jP_cajaLayout.setVerticalGroup(
            jP_cajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_cajaLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(728, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jP_caja);

        jP_inventario.setBackground(new java.awt.Color(248, 248, 248));
        jP_inventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Código", "Descripción", "Stock", "Precio de venta", "<html><p>Precio de Compra</p></html>", "Categoria", "Proveedor", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableInventario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tableInventario);
        if (tableInventario.getColumnModel().getColumnCount() > 0) {
            tableInventario.getColumnModel().getColumn(0).setMinWidth(0);
            tableInventario.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableInventario.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jP_buscadorusuarios1.setBackground(new java.awt.Color(255, 255, 255));
        jP_buscadorusuarios1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel11.setBackground(new java.awt.Color(0, 153, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/magnifyingglass_87552_1.png"))); // NOI18N
        jLabel11.setAlignmentX(0.5F);

        txt_buscador_inventario.setText("Buscar producto..");
        txt_buscador_inventario.setBorder(null);
        txt_buscador_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscador_inventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_buscadorusuarios1Layout = new javax.swing.GroupLayout(jP_buscadorusuarios1);
        jP_buscadorusuarios1.setLayout(jP_buscadorusuarios1Layout);
        jP_buscadorusuarios1Layout.setHorizontalGroup(
            jP_buscadorusuarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_buscadorusuarios1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_buscador_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jP_buscadorusuarios1Layout.setVerticalGroup(
            jP_buscadorusuarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscador_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_nvprod_inv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_nvprod_inv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_nvprod_inv.setText("Nuevo producto");

        jLabel5.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel5.setText("Inventario");

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 474, Short.MAX_VALUE)
                .addComponent(btn_nvprod_inv, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jP_buscadorusuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jP_buscadorusuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_nvprod_inv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jP_inventario.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 1170, 610));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_pags_inv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_pags_inv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_pags_inv.setText("1 de 35");
        jPanel6.add(jLabel_pags_inv, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 8, 215, 27));

        btn_anteriorpag_inv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_anteriorpag_inv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_anteriorpag_inv.setText("Anterior");
        jPanel6.add(btn_anteriorpag_inv, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 8, 70, 27));

        btn_sigpag_inv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sigpag_inv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_sigpag_inv.setText("Siguiente");
        jPanel6.add(btn_sigpag_inv, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 8, 70, 27));

        jP_inventario.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 690, 1170, 40));

        jTabbedPane1.addTab("tab2", jP_inventario);

        jP_clientes.setBackground(new java.awt.Color(248, 248, 248));

        jLabel14.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel14.setText("Clientes");

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Nombre", "NIT", "Telefono", "Dirección", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableClientes.setFocusable(false);
        tableClientes.setGridColor(new java.awt.Color(0, 0, 0));
        tableClientes.setRowHeight(30);
        tableClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tableClientes.setShowGrid(false);
        scroll_clientes.setViewportView(tableClientes);
        if (tableClientes.getColumnModel().getColumnCount() > 0) {
            tableClientes.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableClientes.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        btn_registrarcliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_registrarcliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_registrarcliente.setText("Registrar cliente");
        btn_registrarcliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_registrarcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarclienteMouseClicked(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jP_buscadorcliente.setBackground(new java.awt.Color(255, 255, 255));
        jP_buscadorcliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel3.setBackground(new java.awt.Color(0, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/magnifyingglass_87552_1.png"))); // NOI18N
        jLabel3.setAlignmentX(0.5F);

        txt_buscador_cliente.setBorder(null);
        txt_buscador_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscador_clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_buscadorclienteLayout = new javax.swing.GroupLayout(jP_buscadorcliente);
        jP_buscadorcliente.setLayout(jP_buscadorclienteLayout);
        jP_buscadorclienteLayout.setHorizontalGroup(
            jP_buscadorclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_buscadorclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_buscador_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jP_buscadorclienteLayout.setVerticalGroup(
            jP_buscadorclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscador_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jP_clientesLayout = new javax.swing.GroupLayout(jP_clientes);
        jP_clientes.setLayout(jP_clientesLayout);
        jP_clientesLayout.setHorizontalGroup(
            jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_clientesLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_clientesLayout.createSequentialGroup()
                        .addGroup(jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_registrarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jP_buscadorcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scroll_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 1192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(3157, Short.MAX_VALUE))
        );
        jP_clientesLayout.setVerticalGroup(
            jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_clientesLayout.createSequentialGroup()
                .addGroup(jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_clientesLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(btn_registrarcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(jP_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_clientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jP_buscadorcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(scroll_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jP_clientes);

        jP_usuarios.setBackground(new java.awt.Color(248, 248, 248));

        jLabel13.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel13.setText("Usuarios");

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Nombre", "Telefono", "Usuario", "Permisos", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableUsuarios.setFocusable(false);
        tableUsuarios.setGridColor(new java.awt.Color(0, 0, 0));
        tableUsuarios.setRowHeight(30);
        tableUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tableUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableUsuarios.setShowGrid(false);
        scroll_usuarios.setViewportView(tableUsuarios);

        btn_registrarusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_registrarusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_registrarusuario.setText("Registrar usuario");
        btn_registrarusuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_registrarusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registrarusuarioMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jP_buscadorusuarios.setBackground(new java.awt.Color(255, 255, 255));
        jP_buscadorusuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/magnifyingglass_87552_1.png"))); // NOI18N
        jLabel1.setAlignmentX(0.5F);

        txt_buscadorp_usuario.setBorder(null);
        txt_buscadorp_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscadorp_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_buscadorusuariosLayout = new javax.swing.GroupLayout(jP_buscadorusuarios);
        jP_buscadorusuarios.setLayout(jP_buscadorusuariosLayout);
        jP_buscadorusuariosLayout.setHorizontalGroup(
            jP_buscadorusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_buscadorusuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_buscadorp_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jP_buscadorusuariosLayout.setVerticalGroup(
            jP_buscadorusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_buscadorp_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jP_usuariosLayout = new javax.swing.GroupLayout(jP_usuarios);
        jP_usuarios.setLayout(jP_usuariosLayout);
        jP_usuariosLayout.setHorizontalGroup(
            jP_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_usuariosLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jP_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jP_usuariosLayout.createSequentialGroup()
                        .addGroup(jP_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jP_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_registrarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jP_buscadorusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scroll_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 1192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(3157, Short.MAX_VALUE))
        );
        jP_usuariosLayout.setVerticalGroup(
            jP_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_usuariosLayout.createSequentialGroup()
                .addGroup(jP_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_usuariosLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jP_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(btn_registrarusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(jP_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_usuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jP_buscadorusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(scroll_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jP_usuarios);

        jLabel7.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel7.setText("Configuración");

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jP_confiLayout = new javax.swing.GroupLayout(jP_confi);
        jP_confi.setLayout(jP_confiLayout);
        jP_confiLayout.setHorizontalGroup(
            jP_confiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_confiLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jP_confiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(4221, Short.MAX_VALUE))
        );
        jP_confiLayout.setVerticalGroup(
            jP_confiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_confiLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(728, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jP_confi);

        jLabel9.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel9.setText("Configuración");

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jP_HistorialVentasLayout = new javax.swing.GroupLayout(jP_HistorialVentas);
        jP_HistorialVentas.setLayout(jP_HistorialVentasLayout);
        jP_HistorialVentasLayout.setHorizontalGroup(
            jP_HistorialVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_HistorialVentasLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jP_HistorialVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(4221, Short.MAX_VALUE))
        );
        jP_HistorialVentasLayout.setVerticalGroup(
            jP_HistorialVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_HistorialVentasLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(728, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jP_HistorialVentas);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -51, -1, 890));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL_wallpaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_wallpaperMouseClicked
    }//GEN-LAST:event_jL_wallpaperMouseClicked

    private void btn_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseClicked
        SwingUtilities.invokeLater(() -> {
            jP_menuprincipal.requestFocus();
            mostrar_menu();
        });

    }//GEN-LAST:event_btn_menuMouseClicked

    private void jP_sombreadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jP_sombreadoMouseClicked
        ocultar_menu();
    }//GEN-LAST:event_jP_sombreadoMouseClicked

    private void jL_cajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cajaMouseClicked
        ocultar_menu();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jL_cajaMouseClicked

    private void jL_inventariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_inventariosMouseClicked
        ocultar_menu();
        jTabbedPane1.setSelectedIndex(2);

        Runnable r = new Runnable() {
            @Override
            public void run() {
                inventario.tabledates("", 0);
            }
        };
        Thread th = new Thread(r);
        th.start();


    }//GEN-LAST:event_jL_inventariosMouseClicked

    private void jL_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_clientesMouseClicked
        ocultar_menu();
        clientes.tabledates("");
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jL_clientesMouseClicked

    private void jL_cerrarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_cerrarsesionMouseClicked
        ocultar_menu();
        cerrarSesion();
    }//GEN-LAST:event_jL_cerrarsesionMouseClicked

    private void jL_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_ventasMouseClicked
        ocultar_menu();
        Autocompleter.llenarbusc();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jL_ventasMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        //jPanel7.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txt_buscadorproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscadorproductosMouseClicked

    }//GEN-LAST:event_txt_buscadorproductosMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        jLabel8.setVisible(false);
        txt_buscadorproductos.requestFocus();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void txt_buscadorproductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscadorproductosKeyReleased
        if (txt_buscadorproductos.getText().trim().equals("")) {
            jLabel8.setVisible(true);
            txt_buscadorproductos.setText("");
        } else {
            jLabel8.setVisible(false);
        }
    }//GEN-LAST:event_txt_buscadorproductosKeyReleased

    private void txt_buscadorproductosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscadorproductosFocusLost
        if (txt_buscadorproductos.getText().trim().equals("")) {
            jLabel8.setVisible(true);
            txt_buscadorproductos.setText("");
        }
    }//GEN-LAST:event_txt_buscadorproductosFocusLost

    private void jMenuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEliminarActionPerformed
        Venta.eliminarpro();
    }//GEN-LAST:event_jMenuItemEliminarActionPerformed

    private void jMenuItemeliminartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemeliminartodoActionPerformed
        Venta.eliminarproall();
    }//GEN-LAST:event_jMenuItemeliminartodoActionPerformed

    private void jL_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_usuariosMouseClicked
        ocultar_menu();
        jTabbedPane1.setSelectedIndex(4);
        usuarios.tabledates("");
    }//GEN-LAST:event_jL_usuariosMouseClicked

    private void txt_buscadorp_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscadorp_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscadorp_usuarioActionPerformed

    private void btn_registrarusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarusuarioMouseClicked

    }//GEN-LAST:event_btn_registrarusuarioMouseClicked

    private void jL_configuracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_configuracionMouseClicked

    }//GEN-LAST:event_jL_configuracionMouseClicked

    private void txt_buscador_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscador_inventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscador_inventarioActionPerformed

    private void btn_registrarclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarclienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarclienteMouseClicked

    private void txt_buscador_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscador_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscador_clienteActionPerformed

    private void item_addStock_invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_addStock_invActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_addStock_invActionPerformed

    private void item_editar_invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_editar_invActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_editar_invActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Home home = new Home();
                home.setVisible(true);

                JLayeredPane layered = home.getLayeredPane();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btn_anteriorpag_inv;
    private javax.swing.JLabel btn_menu;
    public javax.swing.JLabel btn_nvprod_inv;
    public javax.swing.JLabel btn_registrarcliente;
    public javax.swing.JLabel btn_registrarusuario;
    public javax.swing.JLabel btn_sigpag_inv;
    public javax.swing.JMenuItem item_addStock_inv;
    public javax.swing.JMenuItem item_editar_inv;
    public javax.swing.JMenuItem item_estado_inv;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jL_caja;
    private javax.swing.JLabel jL_cerrarsesion;
    private javax.swing.JLabel jL_clientes;
    private javax.swing.JLabel jL_configuracion;
    private javax.swing.JLabel jL_inventarios;
    public javax.swing.JLabel jL_totalapagar;
    public javax.swing.JLabel jL_usuarios;
    private javax.swing.JLabel jL_ventas;
    private javax.swing.JLabel jL_wallpaper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabel_pags_inv;
    private javax.swing.JMenuItem jMenuItemEliminar;
    private javax.swing.JMenuItem jMenuItemeliminartodo;
    private javax.swing.JPanel jP_HistorialVentas;
    private javax.swing.JPanel jP_buscadorcliente;
    private javax.swing.JPanel jP_buscadorusuarios;
    private javax.swing.JPanel jP_buscadorusuarios1;
    private javax.swing.JPanel jP_caja;
    private javax.swing.JPanel jP_clientes;
    private javax.swing.JPanel jP_confi;
    private javax.swing.JPanel jP_inventario;
    private javax.swing.JPanel jP_menuprincipal;
    private javax.swing.JPanel jP_sombreado;
    private javax.swing.JPanel jP_usuarios;
    private javax.swing.JPanel jP_ventas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JPopupMenu jPopupInventario;
    private javax.swing.JPopupMenu jPopupNventa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane scroll_clientes;
    private javax.swing.JScrollPane scroll_usuarios;
    public javax.swing.JTable tableClientes;
    public javax.swing.JTable tableInventario;
    public javax.swing.JTable tableNventa;
    public javax.swing.JTable tableUsuarios;
    public javax.swing.JTextField txt_buscador_cliente;
    public javax.swing.JTextField txt_buscador_inventario;
    public javax.swing.JTextField txt_buscadorp_usuario;
    public javax.swing.JTextField txt_buscadorproductos;
    // End of variables declaration//GEN-END:variables

    private void mostrar_menu() {
        if (!menu) {
            menu = true;
            jP_sombreado.setVisible(true);
            repaint();
            Animacion.Animacion.mover_derecha(-200, 0, 1, 1, jP_menuprincipal);
        }
    }

    private void ocultar_menu() {
        if (menu) {
            menu = false;
            jP_sombreado.setVisible(false);
            repaint();
            Animacion.Animacion.mover_izquierda(0, -200, 1, 1, jP_menuprincipal);
        }
    }

    private void menu_roll() {

        ///btns
        Tools.btns(jL_ventas, new Color(33, 45, 62), new Color(53, 65, 82), new Color(73, 85, 102));
        Tools.btns(jL_caja, new Color(33, 45, 62), new Color(53, 65, 82), new Color(73, 85, 102));
        Tools.btns(jL_inventarios, new Color(33, 45, 62), new Color(53, 65, 82), new Color(73, 85, 102));
        Tools.btns(jL_clientes, new Color(33, 45, 62), new Color(53, 65, 82), new Color(73, 85, 102));
        Tools.btns(jL_usuarios, new Color(33, 45, 62), new Color(53, 65, 82), new Color(73, 85, 102));
        Tools.btns(jL_cerrarsesion, new Color(33, 45, 62), new Color(53, 65, 82), new Color(73, 85, 102));
        Tools.btns(jL_configuracion, new Color(33, 45, 62), new Color(53, 65, 82), new Color(73, 85, 102));

        if (userAuth.getRoll().equals("Administrador")) {
            jL_configuracion.setVisible(true);
            jL_usuarios.setVisible(true);
        } else {
            jL_usuarios.setVisible(false);
            jL_configuracion.setVisible(false);
        }
    }

    private void cerrarSesion() {
        int resp = JOptionPane.showConfirmDialog(null, "¿Deseas cerra sesión?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            this.dispose();
            new Login().setVisible(true);
        }
    }

}
